### ISSUE TITLE
Fly [FALSE POSITIVE]

### ISSUE THREAD

**Issue by ExceptedPrism3** [NikV2/CardinalAPI#9]
**Discord**
Prism3#0003

**How/When does it happen?**
About the tp back the set up spawn point in that mili little second upon joining

**Verbose**
https://pastebin.com/TU4PRf1c

**Video of the false positive**
-

**Does the issue still persist on the default config?**
Yes

**Is the plugin up to date?**
Yes

**Is ProtocolLib up to date?**
Yes

**Server Environment & Version**
Spigot 1.8

**Additional Information (Optional)**

**Comment by NikV2** [comment]
What's the name of the plugin that's doing the teleportations?

**Comment by ExceptedPrism3** [comment]
Using this: https://dev.bukkit.org/projects/spawntp

**Comment by NikV2** [comment]
The plugin needs to include TeleportCause.PLUGIN on teleportations to make it compatible with other plugins (Which this one doesn't), Such as Matrix and Cardinal. That's why teleportations such as essential's auto spawn do not false flag, I also noticed it hasn't been updated since Jan 15, 2014 so.. ;p

**Comment by NikV2** [comment]
In the meantime, i'll see if i can exempt unknown teleportation types without opening any bypasses. But in the meantime u should definitely look for a different plugin, That one is extremely outdated

**Comment by ExceptedPrism3** [comment]
How about this: https://www.spigotmc.org/resources/spawntp.13527/ ?

**Comment by NikV2** [comment]
Give it a try, at least this one seems to be getting updates.
